import { BuySell } from "./types";

export const dataBuySell: BuySell[] = [
  {
    avgTradeSizeMM: 4.3,
    byAssetClass: { Credit: 210.4, Rates: 28.2, Derivatives: 39.6 },
    bySideCounts: { buy: 37, sell: 35 },
    commissionsK: 128.0,
    filledOrders: 64,
    fillRatePct: 88.9,
    fund: "Alpha Credit Fund",
    largestTradeMM: 22.5,
    netFlowMM: 13.4,
    numOrders: 72,
    pendingNotionalMM: 18.7,
    primaryBroker: "JPM",
    slippageBps_vsArrival: -4.0,
    strategy: "Credit RV",
    topInstruments: ["HYG US", "LQD US", "CDX IG"],
    totalBuysMM: 145.8,
    totalSellsMM: 132.4,
    tradeTags: ["Relative Value", "Hedging", "Liquidity"],
    venueMix: { ATS: 22, Dark: 41, Lit: 37 },
  },
  {
    avgTradeSizeMM: 6.1,
    byAssetClass: { Rates: 268.9, FX: 188.7, Equity: 82.1, Commodities: 71.5 },
    bySideCounts: { buy: 46, sell: 49 },
    commissionsK: 214.0,
    filledOrders: 79,
    fillRatePct: 83.2,
    fund: "Beta Macro Fund",
    largestTradeMM: 48.0,
    netFlowMM: -32.2,
    numOrders: 95,
    pendingNotionalMM: 42.3,
    primaryBroker: "GS",
    slippageBps_vsArrival: -7.5,
    strategy: "Global Macro",
    topInstruments: ["RX1 Comdty", "ES1 Index", "EURUSD Curncy"],
    totalBuysMM: 289.5,
    totalSellsMM: 321.7,
    tradeTags: ["Macro Tilt", "FX Rebalance", "Carry"],
    venueMix: { ATS: 12, Dark: 18, Lit: 70 },
  },
  {
    avgTradeSizeMM: 2.3,
    byAssetClass: { Equity: 731.9, Derivatives: 79.2 },
    bySideCounts: { buy: 97, sell: 91 },
    commissionsK: 352.0,
    filledOrders: 176,
    fillRatePct: 93.6,
    fund: "Gamma L/S Equity",
    largestTradeMM: 19.4,
    netFlowMM: 14.7,
    numOrders: 188,
    pendingNotionalMM: 11.8,
    primaryBroker: "MS",
    slippageBps_vsArrival: -6.2,
    strategy: "L/S Equity",
    topInstruments: ["AAPL US", "MSFT US", "NVDA US"],
    totalBuysMM: 412.9,
    totalSellsMM: 398.2,
    tradeTags: ["Alpha Rotation", "Factor Tilt", "Earnings"],
    venueMix: { ATS: 28, Dark: 46, Lit: 26 },
  },
  {
    avgTradeSizeMM: 3.8,
    byAssetClass: { Rates: 221.7, Credit: 72.5, Derivatives: 51.7 },
    bySideCounts: { buy: 44, sell: 40 },
    commissionsK: 111.0,
    filledOrders: 76,
    fillRatePct: 90.5,
    fund: "Delta FI Arb",
    largestTradeMM: 27.6,
    netFlowMM: 31.3,
    numOrders: 84,
    pendingNotionalMM: 14.2,
    primaryBroker: "BAML",
    slippageBps_vsArrival: -2.1,
    strategy: "Fixed Income Arb",
    topInstruments: ["UST 5Y", "UST 10Y", "ED Z6"],
    totalBuysMM: 188.6,
    totalSellsMM: 157.3,
    tradeTags: ["Basis", "Curve", "Spread"],
    venueMix: { ATS: 9, Dark: 22, Lit: 69 },
  },
  {
    avgTradeSizeMM: 5.7,
    byAssetClass: { Credit: 187.2, Private: 18.1 },
    bySideCounts: { buy: 18, sell: 23 },
    commissionsK: 141.0,
    filledOrders: 33,
    fillRatePct: 80.5,
    fund: "Epsilon Distressed",
    largestTradeMM: 36.8,
    netFlowMM: -25.3,
    numOrders: 41,
    pendingNotionalMM: 28.9,
    primaryBroker: "UBS",
    slippageBps_vsArrival: -18.3,
    strategy: "Distressed / Special Sits",
    topInstruments: ["XYZ 8.25% 2029", "ABC TL B", "DEF 2L"],
    totalBuysMM: 96.2,
    totalSellsMM: 121.5,
    tradeTags: ["Event", "Work-out", "Block"],
    venueMix: { ATS: 6, Dark: 38, Lit: 56 },
  },
  {
    avgTradeSizeMM: 0.9,
    byAssetClass: { Equity: 90.4, Derivatives: 25.7 },
    bySideCounts: { buy: 66, sell: 66 },
    commissionsK: 118.0,
    filledOrders: 125,
    fillRatePct: 94.7,
    fund: "Zeta Market Neutral",
    largestTradeMM: 6.5,
    netFlowMM: 0.5,
    numOrders: 132,
    pendingNotionalMM: 3.1,
    primaryBroker: "Barclays",
    slippageBps_vsArrival: -3.7,
    strategy: "Equity Market Neutral",
    topInstruments: ["SPY US", "QQQ US", "IWM US"],
    totalBuysMM: 58.3,
    totalSellsMM: 57.8,
    tradeTags: ["Rebalance", "Hedging", "StatArb"],
    venueMix: { ATS: 35, Dark: 49, Lit: 16 },
  },
  {
    avgTradeSizeMM: 3.7,
    byAssetClass: { Credit: 187.6, Derivatives: 76.1 },
    bySideCounts: { buy: 30, sell: 28 },
    commissionsK: 126.0,
    filledOrders: 50,
    fillRatePct: 86.2,
    fund: "Eta Structured Credit",
    largestTradeMM: 24.3,
    netFlowMM: 4.5,
    numOrders: 58,
    pendingNotionalMM: 12.9,
    primaryBroker: "CS",
    slippageBps_vsArrival: -9.1,
    strategy: "Structured Credit",
    topInstruments: ["ABX IG", "CMBX BBB-", "RMBS 2.0"],
    totalBuysMM: 134.1,
    totalSellsMM: 129.6,
    tradeTags: ["Spread", "Carry", "Roll"],
    venueMix: { ATS: 4, Dark: 33, Lit: 63 },
  },
  {
    avgTradeSizeMM: 4.2,
    byAssetClass: { Commodities: 336.8, Derivatives: 132.5 },
    bySideCounts: { buy: 37, sell: 40 },
    commissionsK: 137.0,
    filledOrders: 67,
    fillRatePct: 87.0,
    fund: "Theta Commodities",
    largestTradeMM: 39.5,
    netFlowMM: -18.5,
    numOrders: 77,
    pendingNotionalMM: 21.4,
    primaryBroker: "BAML",
    slippageBps_vsArrival: -11.9,
    strategy: "Commodities",
    topInstruments: ["CL1 Comdty", "GC1 Comdty", "HG1 Comdty"],
    totalBuysMM: 225.4,
    totalSellsMM: 243.9,
    tradeTags: ["Curve Roll", "Hedge", "Momentum"],
    venueMix: { ATS: 0, Dark: 12, Lit: 88 },
  },
  {
    avgTradeSizeMM: 1.3,
    byAssetClass: { Equity: 84.6, Rates: 122.7, FX: 37.2, Derivatives: 125.8 },
    bySideCounts: { buy: 80, sell: 84 },
    commissionsK: 162.0,
    filledOrders: 153,
    fillRatePct: 93.3,
    fund: "Iota Quant Multi-Asset",
    largestTradeMM: 11.1,
    netFlowMM: -12.5,
    numOrders: 164,
    pendingNotionalMM: 8.4,
    primaryBroker: "GS",
    slippageBps_vsArrival: -2.9,
    strategy: "Quant Multi-Asset",
    topInstruments: ["ZB1 Comdty", "NQ1 Index", "GBPUSD Curncy"],
    totalBuysMM: 178.9,
    totalSellsMM: 191.4,
    tradeTags: ["Model Refresh", "Rebalance", "Risk Parity"],
    venueMix: { ATS: 31, Dark: 43, Lit: 26 },
  },
  {
    avgTradeSizeMM: 6.0,
    byAssetClass: { Private: 54.1, Credit: 48.0 },
    bySideCounts: { buy: 12, sell: 6 },
    commissionsK: 89.0,
    filledOrders: 14,
    fillRatePct: 77.8,
    fund: "Kappa Private Credit",
    largestTradeMM: 28.0,
    netFlowMM: 32.7,
    numOrders: 18,
    pendingNotionalMM: 21.9,
    primaryBroker: "JPM",
    slippageBps_vsArrival: -24.6,
    strategy: "Private Credit",
    topInstruments: ["Unitranche A", "2L Term Loan", "PIK Note 2029"],
    totalBuysMM: 67.4,
    totalSellsMM: 34.7,
    tradeTags: ["Primary Alloc", "Work-out", "Amend/Extend"],
    venueMix: { ATS: 0, Dark: 21, Lit: 79 },
  },
];
