export interface ReturnsTDData {
  /** Assets under management */
  aum: number;
  /** Bond Equivalent Yield */
  bey: number;
  /** Cost of Funds */
  cof: number;
  convexity: number;
  date: string;
  duration: number;
  exposureGross: number;
  exposureNet: number;
  fund: string;
  investorLiquidity: number;
  last18mo: number[];
  leverage: number;
  /** Last Twelve Months */
  ltm: number;
  /** Month-to-date Change */
  mtd: number;
  sp500beta: number;
  spreadDuration: number;
  strategy: string;
  /** Income generated by fund's investmentss */
  yield: number;
  /** Year-to-date Change */
  ytd: number;
}
